---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: bazzite-at-home
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/bazzite-dx
image-version: latest

modules:
  - type: script
    snippets:
      - "mkdir /nix"
  - type: files
    files:
      - source: system
        destination: /
  - type: justfiles
    validate: true
  - type: dnf
    install:
      packages:
        - virt-manager
        - edk2-ovmf
        - qemu
        - git-lfs
        - git-delta
        - patch
    remove:
      packages:
        - firefox
        - firefox-langpacks
  - type: signing
  - type: dnf
    repos:
      files:
        - terra.repo
    install:
      packages:
        - zed
  - type: dnf
    repos:
      copr:
        - wezfurlong/wezterm-nightly
    install:
      packages:
        - wezterm
